project_name: k8ssandra-client
builds:
  id: "kubectl-k8ssandra"
  main: cmd/kubectl-k8ssandra/main.go
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath

# proxies from the go mod proxy before building
# https://goreleaser.com/customization/gomod
gomod:
  proxy: true

# config the checksum filename
# https://goreleaser.com/customization/checksum
checksum:
  name_template: 'checksums.txt'

# create a source tarball
# https://goreleaser.com/customization/source/
source:
  enabled: true